#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: Build_x86_64

on: 
  release:
    types: [published]

  # 编辑触发
  #push:
    #branches: 
      #- master

  # 定时触发()
  #schedule:
  #  - cron: 0 8 * * 5
  
  watch:
    types: [started]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 校验本地文件
      uses: actions/checkout@master

    - name: Initialization environment 初始化编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev patch unzip lib32gcc1 libc6-dev-i386 subversion flex node-uglify gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils  libelf-dev autoconf automake libtool autopoint device-tree-compiler libuv-dev python3.6 zlib1g-dev upx-ucl node-uglify antlr3 gperf
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code 克隆源代码
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master            
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        sed -i '5s/#//' feeds.conf.default
   
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a

    - name: Import external feeds
      working-directory: ./openwrt
      run: |
        git clone https://github.com/Lienol/openwrt-package package/openwrt-package
        git clone https://github.com/kenzok8/openwrt-packages package/kenzok8
        git clone https://github.com/jerrykuku/luci-app-vssr package/luci-app-vssr
        git clone https://github.com/jerrykuku/lua-maxminddb package/lua-maxminddb  #git luci-app-vssr 依赖
        git clone https://github.com/lisaac/luci-lib-docker package/luci-lib-docker #git luci-app-dockerman 依赖
        git clone https://github.com/lisaac/luci-app-dockerman package/luci-app-dockerman   
         
        #passwall 3.6-40 版本有一个选项是“使用ipv6” 可以让域名解析为ipv6进行连接
        #git clone https://github.com/NANXIAO1971/passwall package/passwall
        #git clone https://github.com/kenzok8/small package/small
        #git clone https://github.com/frainzy1477/luci-app-clash package/luci-app-clash       
        #git clone -b master --single-branch https://github.com/vernesong/OpenClash package/openclash
        #git clone https://github.com/rufengsuixing/luci-app-adguardhome package/luci-app-adguardhome
        #git clone https://github.com/garypang13/luci-app-eqos package/luci-app-eqos     
    
        git clone https://github.com/shadowsocks/openwrt-feeds package/dnscrypt-proxy2   # 添加 feeds/libsodium 
        rm -rf package/dnscrypt-proxy2/packages/libcares    
        git clone https://github.com/peter-tank/openwrt-minisign package/dnscrypt-proxy2/minisign    # 获取 minisign Makefile
        git clone https://github.com/peter-tank/luci-app-dnscrypt-proxy2 package/luci-app-dnscrypt-proxy2
                
        git clone https://github.com/xiaoqingfengATGH/luci-theme-infinityfreedom package/luci-theme-infinityfreedom
        git clone -b 18.06 --single-branch https://github.com/jerrykuku/luci-theme-argon package/luci-theme-argon--cpboy-mod
        git clone https://github.com/esirplayground/luci-theme-atmaterial-ColorIcon package/luci-theme-atmaterial-ColorIcon
        #git clone "your_github_link" package/"your_folder_name"   
        # 再次更新并安装源
        ./scripts/feeds clean
        ./scripts/feeds update -a && ./scripts/feeds install -a
        
    #- name: Prepare feeds
      #run: cd openwrt && ./prepareCompile.sh
    #- name: modify feeds 修改插件分类 
      #working-directory: ./openwrt
      #run: |
        #chmod +x ./cpboydiy.sh && ./cpboydiy.sh

    - name: Configuration Customization - Build_x86_64
      env:
        CONFIG_FILE: 'x86_64.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
        
    - name: Download package 下载软件包
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build firmware Multi-thread compile 多线程编译固件
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
          
    - name: Single-thread compile 单线程编译固件
      working-directory: ./openwrt
      if: failure()
      run: |
        make -j1 V=s
          
    - name: Assemble artifact
      run: |
        rm -rf ./artifact/
        mkdir -p ./artifact/
        find openwrt/bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/
        find openwrt/bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt-x86-64 firmware
        path: ./artifact/
        
